### PR TITLE
Add roles & icons for Reaper (RPR) and Sage (SGE)

### LINKED ISSUE #142: cactbot started reporting errors after updating
cactbot started reporting errors after updating
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'. (Source: , Line: 0)
[2021/12/5 3:28:56] Info:  BrowserConsole: Uncaught Error: Cannot find module './sge.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1)
[2021/12/5 3:28:58] Info:  BrowserConsole: Error: Cannot find module './sge.png' (Source: https://bsides.github.io/horizoverlay/static/js/2.b7868ab6.chunk.js, Line: 1
image

### PR DESCRIPTION
**Pull request by ekumlin**
This change adds roles for the new Endwalker Reaper and Sage classes, as well as icons for the same.

I also adopted a fix to prevent missing icons from breaking the overlay, inspired by [a code snippet provided in #142](https://github.com/bsides/horizoverlay/issues/142#issuecomment-986083807).

Fixes #142.

### CODE REVIEW

**Comment by bsides** [comment]
Nice fix, thanks for the contribution!

**Review by bsides — APPROVED** [review]
Nice fix, thanks for the contribution!

**Comment by haseogu963** [comment]
are these already working in the current version? or your gonna update the overlay at a later date?

**Comment by bsides** [comment]
> are these already working in the current version? or your gonna update the overlay at a later date?

Should be working now. Please report in case it's not. Thank you.
